var blackList = [
    {url:'s.360.cn'},
    {url:'sdk.51.la'},
    {url:'a.ad.gt'},
    {url:'px.ads.linkedin.com'},
    {url:'dc.ads.linkedin.com'},
    {url:'adsrvr.org'},
    {url:'ds-aksb-a.akamaihd.net'},
    {url:'time-ae.akamaized.net'},
    {url:'certify-js.alexametrics.com'},
    {url:'at.alicdn.com'},
    {url:'aeu.alicdn.com'},
    {url:'g.alicdn.com'},
    {url:'amazon-adsystem.com'},
    {url:'analytics.yahoo.com'},
    {url:'sync.aralego.com'},
    {url:'assoc-na.associates-amazon.com'},
    {url:'static.atgsvcs.com'},
    {url:'logws1320.ati-host.net'},
    {url:'fxgate.baidu.com'},
    {url:'datax.baidu.com'},
    {url:'gsp0.baidu.com'},
    {url:'hm.baidu.com'},
    {url:'sp0.baidu.com'},
    {url:'cpro.baidu.com'},
    {url:'passport.baidu.com'},
    {url:'cbjs.baidu.com'},
    {url:'timgsa.baidu.com'},
    {url:'znsv.baidu.com'},
    {url:'bat.bing.com'},
    {url:'sjs.bizographics.com'},
    {url:'ping.chartbeat.net'},
    {url:'cnzz.com'},
    {url:'google-analytics.com'},
    {url:'growingio.com'},
    {url:'mktoresp.com'},
    {url:'mmstat.com'},
    {url:'turn.com'},
    {url:'api.company-target.com'},
    {url:'t.contentsquare.net'},
    {url:'p.cpx.to'},
    {url:'sslwidget.criteo.com'},
    {url:'nyt2.dc-storm.com'},
    {url:'dpm.demdex.net'},
    {url:'servedby.flashtalking.com'},
    {url:'gateway.foresee.com'},
    {url:'static.getclicky.com'},
    {url:'analytics.google.com'},
    {url:'stats.hanmaker.com'},
    {url:'track.hubspot.co'},
    {url:'fm.ipinyou.com'},
    {url:'pt.ispot.tv'},
    {url:'cdn.krxd.net'},
    {url:'app.leadsrx.com'},
    {url:'app.link'},
    {url:'platform.linkedin.com'},
    {url:'service.maxymiser.net'},
    {url:'show-3.mediav.com'},
    {url:'show-g.mediav.com'},
    {url:'t.myvisualiq.net'},
    {url:'vt.myvisualiq.net'},
    {url:'doubleclick.net'},
    {url:'omtrdc.net'},
    {url:'bam-cell.nr-data.net'},
    {url:'pi.pardot.com'},
    {url:'report.passport.360.cn'},
    {url:'ct.pinterest.com'},
    {url:'cm.pos.baidu.com'},
    {url:'match.prod.bidr.io'},
    {url:'a.pub.network'},
    {url:'ads.pubmatic.com'},
    {url:'sqimg.qq.com'},
    {url:'aegis.qq.com'},
    {url:'wpa.qq.com'},
    {url:'pingjs.qq.com'},
    {url:'3gimg.qq.com'},
    {url:'secure.quantserve.com'},
    {url:'edge.quantserve.com'},
    {url:'pixel.quantserve.com'},
    {url:'q.quora.com'},
    {url:'a.quora.com'},
    {url:'ct1.ra.linksynergy.com'},
    {url:'id.rlcdn.com'},
    {url:'idsync.rlcdn.com'},
    {url:'sb.scorecardresearch.com'},
    {url:'secure-ds.serving-sys.com'},
    {url:'bdimg.share.baidu.com'},
    {url:'mcs.snssdk.com'},
    {url:'i.snssdk.com'},
    {url:'w.soundcloud.com'},
    {url:'secure.statcounter.com'},
    {url:'dx.steelhousemedia.com'},
    {url:'s754876867.t.eloqua.com'},
    {url:'pixel.tapad.com'},
    {url:'analytics.tiktok.com'},
    {url:'h.trace.qq.com'},
    {url:'s.tribalfusion.com'},
    {url:'collector-1594.tvsquared.com'},
    {url:'s.union.360.cn'},
    {url:'trkn.us'},
    {url:'js.users.51.la'},
    {url:'dev.visualwebsiteoptimizer.com'},
    {url:'cl2.webterren.com'},
    {url:'mp.weixin.qq.com'},
    {url:'res.wx.qq.com'},
    {url:'resources.xg4ken.com'},
    {url:'aqyzmedia.yunaq.com'},
    {url:'ush.zhanzhang.baidu.com'},
    {url:'push.zhanzhang.baidu.com'},
    {url:'ws.zoominfo.com'}
];

function FindProxyForURL(url, host){
    var direct = 'DIRECT;';
    var proxy = '8.8.8.8';
    var block = '8.8.8.8';
    
        for(i in blackList){
            if(blackList[i].url){
                if(url.indexOf(blackList[i].url) > -1){
                    return 'PROXY '+ block +';';
                };
            };
            if(blackList[i].domain){
                if(shExpMatch(host, blackList[i].domain)){
                    return 'PROXY '+ block +';';
                };
            };
        };
    return direct;
}
