// 多语言
const localizeLanguage = {
  en: {
    extName: 'Background Color Post',
    title: 'Extension not installed',
    description: 'Install the extension from the Google Chrome store and refresh this page to use it.',
    download: 'Download',
    postContent: 'Content',
    enterContent: 'Enter your content here',
    dropImage: 'Drop image here',
    or: 'or',
    selectImage: 'Select Image',
    selectBackground: '🎨 Select Background',
    preview: 'Preview >',
    scheduledSend: '⏰ Scheduled Post',
    selectPublishTime: 'Select publish time',
    post: 'Post',
    addToQueue: 'Add to Schedule',
    groupListPane: 'Group List',
    customGroupId: 'Custom Group ID',
    scheduledTask: 'Scheduled Tasks',
    group: 'Group',
    getGroup: 'Get Group',
    option: 'Option',
    avatar: 'Avatar',
    groupName: 'Group Name',
    enterGroupId: 'Enter group IDs (one per line)',
    status: 'Status',
    time: 'Time',
    background: 'Background',
    content: 'Content',
    target: 'Target',
    action: 'Action',
    selectBackgroundStyle: 'Select Background',
    maxImagesSelected: 'You can select up to @ images. Only the first @ images were used.',
    deleteScheduledTasksConfirm: 'Are you sure you want to delete the selected scheduled tasks?',
    deleteScheduledTasks: '@ tasks have been deleted',
    pending: 'Pending',
    processing: 'Processing',
    success: 'Success',
    failed: 'Failed',
    expired: 'Expired',
    error: 'Error',
    groupCount: '@ groups',
    timeline: 'Timeline',
    search: '🔍 Search keywords or image elements...',
    '3D': '3D',
    illustration: 'Illustration',
    pureColor: 'Pure Color',
    animal: 'Animal',
    landscape: 'Landscape',
    flower: 'Flower',
    texture: 'Gexture',
    gradient: 'Gradient',
    festival: 'Festival',
    other: 'Ohter',
    food: 'Food',
    fruit: 'Fruit',
    sport: 'Sport',
    pattern: 'Pattern',
    messageBubble: 'Message bubble',
    heartPattern: 'Heart pattern',
    starrySky: 'Starry Sky',
    virtualAvatar: 'Virtual avatar',
    plant: 'Plant'
  },
  zh: {
    extName: '彩色背景帖子',
    title: '未安装扩展程序',
    description: '从 Google Chrome 商店安装扩展程序，刷新此页面后即可正常使用。',
    download: '下载',
    postContent: '帖文内容',
    enterContent: '请输入需要发布的内容',
    dropImage: '拖入图片',
    or: '或',
    selectImage: '选择图片',
    selectBackground: '🎨 选择彩色背景',
    preview: '预览 >',
    scheduledSend: '⏰ 定时发送',
    selectPublishTime: '选择发布时间',
    post: '发布',
    addToQueue: '添加到队列',
    groupListPane: '小组列表',
    customGroupId: '自定义小组 ID',
    scheduledTask: '定时任务',
    group: '小组',
    getGroup: '获取小组',
    option: '选项',
    avatar: '头像',
    groupName: '名称',
    enterGroupId: '输入小组 ID (每行一个)',
    status: '状态',
    time: '时间',
    background: '背景',
    content: '内容',
    target: '目标',
    action: '操作',
    selectBackgroundStyle: '选择背景样式',
    maxImagesSelected: '最多只能选择 @ 张图片，已自动取前 @ 张',
    deleteScheduledTasksConfirm: '确定要批量删除定时任务吗？',
    deleteScheduledTasks: '已删除 @ 个任务',
    pending: '等待中',
    processing: '进行中',
    success: '已发布',
    failed: '失败',
    expired: '逾期',
    error: '异常',
    groupCount: '@ 个小组',
    timeline: '时间线',
    search: '🔍 搜索关键词或图片元素...',
    '3D': '3D',
    illustration: '插画',
    pureColor: '纯色',
    animal: '动物',
    landscape: '风景',
    flower: '花朵',
    texture: '纹理',
    gradient: '渐变',
    festival: '节日',
    other: '其它',
    food: '食物',
    fruit: '水果',
    sport: '体育',
    pattern: '图案',
    messageBubble: '消息气泡',
    heartPattern: '心形图案',
    starrySky: '星空',
    virtualAvatar: '虚拟形象',
    plant: '植物'
  }
}

// 语言初始化
const elements = document.querySelectorAll('[data-localize]')
let browserLang = navigator.language || navigator.userLanguage
browserLang = browserLang.toLowerCase()
const currentLang = browserLang.startsWith('zh') ? 'zh' : 'en'

const localize = localizeLanguage[currentLang]

for (const el of elements) {
  const key = el.getAttribute('data-localize')
  const text = localizeLanguage[currentLang][key]
  if (!text) continue
  if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
    el.placeholder = text
  } else {
    el.innerText = text
  }
}
